// flow-typed signature: fbda683ea8c301543ab7d65d3d98a017
// flow-typed version: <<STUB>>/detect-it_v3.x.x/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "detect-it" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "detect-it/lib/index" {
  declare module.exports: any;
}

declare module "detect-it/src/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "detect-it/lib/index.js" {
  declare module.exports: $Exports<"detect-it/lib/index">;
}
declare module "detect-it/src/index.js" {
  declare module.exports: $Exports<"detect-it/src/index">;
}
