// flow-typed signature: fed14d51bc7e904a1b604588cd47b4fe
// flow-typed version: <<STUB>>/idb-keyval_v3.0.5/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb-keyval'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb-keyval' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idb-keyval/dist/idb-keyval-cjs' {
  declare module.exports: any;
}

declare module 'idb-keyval/dist/idb-keyval-iife-compat.min' {
  declare module.exports: any;
}

declare module 'idb-keyval/dist/idb-keyval-iife' {
  declare module.exports: any;
}

declare module 'idb-keyval/dist/idb-keyval-iife.min' {
  declare module.exports: any;
}

declare module 'idb-keyval/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idb-keyval/dist/idb-keyval-cjs.js' {
  declare module.exports: $Exports<'idb-keyval/dist/idb-keyval-cjs'>;
}
declare module 'idb-keyval/dist/idb-keyval-iife-compat.min.js' {
  declare module.exports: $Exports<'idb-keyval/dist/idb-keyval-iife-compat.min'>;
}
declare module 'idb-keyval/dist/idb-keyval-iife.js' {
  declare module.exports: $Exports<'idb-keyval/dist/idb-keyval-iife'>;
}
declare module 'idb-keyval/dist/idb-keyval-iife.min.js' {
  declare module.exports: $Exports<'idb-keyval/dist/idb-keyval-iife.min'>;
}
declare module 'idb-keyval/rollup.config.js' {
  declare module.exports: $Exports<'idb-keyval/rollup.config'>;
}
