// flow-typed signature: e38af0a31d9efbebae76209f3896cb6b
// flow-typed version: <<STUB>>/measure-text_v0.0.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'measure-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'measure-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'measure-text/dist/measure-text' {
  declare module.exports: any;
}

declare module 'measure-text/dist/measure-text.min' {
  declare module.exports: any;
}

declare module 'measure-text/lib/index' {
  declare module.exports: any;
}

declare module 'measure-text/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'measure-text/dist/measure-text.js' {
  declare module.exports: $Exports<'measure-text/dist/measure-text'>;
}
declare module 'measure-text/dist/measure-text.min.js' {
  declare module.exports: $Exports<'measure-text/dist/measure-text.min'>;
}
declare module 'measure-text/lib/index.js' {
  declare module.exports: $Exports<'measure-text/lib/index'>;
}
declare module 'measure-text/src/index.js' {
  declare module.exports: $Exports<'measure-text/src/index'>;
}
