// flow-typed signature: 8ce0df6192d1f5b0255a5e62a1ff742d
// flow-typed version: <<STUB>>/resize-observer-polyfill_v1.5.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resize-observer-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resize-observer-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resize-observer-polyfill/dist/ResizeObserver.es' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/dist/ResizeObserver.global' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/dist/ResizeObserver' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/index' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/ResizeObservation' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/ResizeObserver' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/ResizeObserverController' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/ResizeObserverEntry' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/ResizeObserverSPI' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/shims/es6-collections' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/shims/global' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/shims/requestAnimationFrame' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/utils/defineConfigurable' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/utils/geometry' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/utils/getWindowOf' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/utils/isBrowser' {
  declare module.exports: any;
}

declare module 'resize-observer-polyfill/src/utils/throttle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resize-observer-polyfill/dist/ResizeObserver.es.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/dist/ResizeObserver.es'>;
}
declare module 'resize-observer-polyfill/dist/ResizeObserver.global.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/dist/ResizeObserver.global'>;
}
declare module 'resize-observer-polyfill/dist/ResizeObserver.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/dist/ResizeObserver'>;
}
declare module 'resize-observer-polyfill/src/index.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/index'>;
}
declare module 'resize-observer-polyfill/src/ResizeObservation.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/ResizeObservation'>;
}
declare module 'resize-observer-polyfill/src/ResizeObserver.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/ResizeObserver'>;
}
declare module 'resize-observer-polyfill/src/ResizeObserverController.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/ResizeObserverController'>;
}
declare module 'resize-observer-polyfill/src/ResizeObserverEntry.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/ResizeObserverEntry'>;
}
declare module 'resize-observer-polyfill/src/ResizeObserverSPI.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/ResizeObserverSPI'>;
}
declare module 'resize-observer-polyfill/src/shims/es6-collections.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/shims/es6-collections'>;
}
declare module 'resize-observer-polyfill/src/shims/global.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/shims/global'>;
}
declare module 'resize-observer-polyfill/src/shims/requestAnimationFrame.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/shims/requestAnimationFrame'>;
}
declare module 'resize-observer-polyfill/src/utils/defineConfigurable.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/utils/defineConfigurable'>;
}
declare module 'resize-observer-polyfill/src/utils/geometry.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/utils/geometry'>;
}
declare module 'resize-observer-polyfill/src/utils/getWindowOf.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/utils/getWindowOf'>;
}
declare module 'resize-observer-polyfill/src/utils/isBrowser.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/utils/isBrowser'>;
}
declare module 'resize-observer-polyfill/src/utils/throttle.js' {
  declare module.exports: $Exports<'resize-observer-polyfill/src/utils/throttle'>;
}
